name: Discord Update Notification

on:
  push:
    branches: [ main ]

jobs:
  discord-notify:
    runs-on: ubuntu-latest
    steps:
      - name: Discord Webhook Action
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          username: "Albion Market System"
          avatar-url: "https://market.majdpro.com/icon.png"
          embed-title: "⚔️ New System Update Applied"
          embed-description: "${{ github.event.head_commit.message }}"
          embed-color: 16096779
          embed-footer-text: "Albion Market System • Automated Feed"
          embed-timestamp: true
